# Generated by Django 5.2 on 2025-04-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('strategie', models.CharField(max_length=20)),
                ('dose_eau', models.FloatField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='CapteurData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('humidite', models.FloatField()),
                ('temperature', models.FloatField()),
                ('salinite', models.FloatField()),
                ('npk', models.CharField(max_length=50)),
                ('eto', models.FloatField(blank=True, null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parcelle')),
            ],
        ),
    ]
