# Generated by Django 5.2 on 2025-04-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='parcelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parcelle'),
        ),
        migrations.AlterField(
            model_name='capteurdata',
            name='parcelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parcelle'),
        ),
        migrations.AlterField(
            model_name='irrigationdecision',
            name='parcelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parcelle'),
        ),
    ]
